name: therapy_calendar
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  built_collection: ^4.3.2
  built_value: ^7.1.0
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.1
  flutter_localizations:
    sdk: flutter
  flutter_picker: ^1.1.5
  intl: ^0.16.1
  intl_translation: ^0.17.10
  intl_utils: ^1.6.3
  sticky_headers: ^0.1.8+1

dev_dependencies:
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

flutter_intl:
  main_locale: de_DE
  enabled: true
